/**
 * StreamVault Edge Worker — SpeedRace + Viduki + Flicky
 * Copyright (c) 2026 Moey.
 *
 * ROUTES:
 *   GET  /viduki/movie/{tmdbId}
 *   GET  /viduki/tv/{tmdbId}/{season}/{episode}
 *   GET  /flicky/movie/{tmdbId}
 *   GET  /flicky/tv/{tmdbId}/{season}/{episode}
 *   GET  /?id=…&type=…&season=…&episode=…   (legacy SpeedRace/TryBox root)
 *
 * All routes return: { sources: [{ url, quality }], subtitles: [] } | { error }.
 *
 * Viduki + Flicky do the full WASM crypto server-side so Android (which has no
 * local Node) can hit the Worker from ExoPlayer's referer-setting HTTP stack
 * and play direct from cdn1.1shows.app — the fat video download bypasses the
 * Worker entirely; only the ~1-second resolve does an edge hop.
 *
 * DEPLOY: paste as `src/index.js` on the Workers dashboard, Save & Deploy.
 * Both WASMs live inline as base64 so the deploy artifact is self-contained.
 * Regenerate this file with `node .tmp/build_worker.js` after replacing the
 * WASM binaries in the repo root.
 */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': '*',
  'Content-Type': 'application/json'
};

const SPEEDRACE_HOST = 'https://api.speedracelight.com';
const SPOOF_ORIGIN = 'https://player.videasy.to';

// ─── SpeedRace mvm1 decryption (unchanged, kept for the legacy root route) ───
const MAGIC_HEADER = [109, 118, 109, 49];
const TABLE_F = [
  1116352408, 1899447441, 3049323471, 3921009573,
  961987163, 1508970993, 2453635748, 2870763221,
  3624381080, 310598401, 607225278, 1426881987,
  1925078388, 2162078206, 2614888103, 3248222580
];
const isEven = (e) => ((e * (e + 1)) & 1) === 0;
const isOdd = (e) => ((e * (e + 1)) & 1) === 1;
function _v(e) {
  e >>>= 0;
  e ^= e >>> 16;
  e = Math.imul(e, 2246822507) >>> 0;
  e ^= e >>> 13;
  e = Math.imul(e, 3266489909) >>> 0;
  return (e ^= e >>> 16) >>> 0;
}
function _w(e, t) {
  e >>>= 0;
  return (0 === (t &= 31)) ? e >>> 0 : ((e << t) | (e >>> (32 - t))) >>> 0;
}
function decodeBase64Url(str) {
  let t = str.replace(/-/g, '+').replace(/_/g, '/').padEnd(4 * Math.ceil(str.length / 4), '=');
  let decoded = atob(t);
  let bytes = new Uint8Array(decoded.length);
  for (let i = 0; i < decoded.length; i++) bytes[i] = decoded.charCodeAt(i);
  return bytes;
}
function decryptPayload(payload, seed, mediaId) {
  const bytes = decodeBase64Url(payload);
  const len = bytes.length;
  const state = (function (seedStr, idNum) {
    if (isOdd(seedStr.length)) {
      const S = (function (s) {
        let arr = new Array(256);
        for (let i = 0; i < 256; i++) arr[i] = i;
        let j = 0;
        for (let i = 0; i < 256; i++) {
          j = (j + arr[i] + s.charCodeAt(i % s.length)) & 255;
          let tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
        }
        return arr;
      })(seedStr);
      const acc = (function (s) {
        let accVal = 1732584193;
        for (let i = 0; i < s.length; i++) {
          accVal = _w((accVal ^ Math.imul(s.charCodeAt(i), TABLE_F[15 & i])) >>> 0, 5);
        }
        return _v(accVal);
      })(seedStr);
      return { S, acc };
    }
    let S = new Array(61);
    let hashSeed = (function (s) {
      let h = 2166136261;
      for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619) >>> 0;
      return _v(h);
    })(seedStr);
    let a = _v(hashSeed ^ _v((idNum >>> 0) ^ 2654435769)) >>> 0;
    for (let i = 0; i < 8; i++) {
      if (isEven(i)) {
        let mod61 = a % 61;
        a = _w((a + 2654435769) >>> 0, 7 + (7 & i));
        S[mod61] = (a ^ _v(a)) >>> 0;
        a = _v((a + mod61) >>> 0);
      } else {
        S[i] = TABLE_F[15 & i];
      }
    }
    return { S, acc: _v((2779096485 ^ a) >>> 0) };
  })(seed, mediaId);
  const genKey = new Uint8Array(len);
  let genIdx = 0;
  for (let i = 0; i < len;) {
    let nextWord = (function (st, idx) {
      let S = st.S;
      let acc = st.acc;
      let modVal = acc % 61;
      let hasKey = 0 - Number(modVal in S);
      let currentWord = S[modVal] >>> 0;
      let calc = (((acc ^ (currentWord ^ Math.imul(2654435769, idx + 1) >>> 0) >>> 0) >>> 0 |
        (acc & (currentWord ^ Math.imul(2654435769, idx + 1) >>> 0) & hasKey) >>> 0)) >>> 0;
      acc = _v((calc = (_w((calc + acc) >>> 0, 31 & modVal) ^ _w(acc, 31 & Math.imul(modVal, 7))) >>> 0) + 2654435769 >>> 0);
      S[modVal] = acc >>> 0;
      st.acc = acc;
      return acc >>> 0;
    })(state, genIdx++);
    genKey[i++] = 255 & nextWord;
    if (i < len) genKey[i++] = (nextWord >>> 8) & 255;
    if (i < len) genKey[i++] = (nextWord >>> 16) & 255;
    if (i < len) genKey[i++] = (nextWord >>> 24) & 255;
  }
  const decrypted = new Uint8Array(len);
  for (let i = 0; i < len; i++) decrypted[i] = bytes[i] ^ genKey[i];
  for (let i = 0; i < MAGIC_HEADER.length; i++) {
    if (decrypted[i] !== MAGIC_HEADER[i]) throw new Error("Bad seed or magic header");
  }
  return new TextDecoder('utf-8').decode(decrypted.subarray(MAGIC_HEADER.length));
}

// ─── byte helpers (Buffer-free, work in Workers) ─────────────────────────────
function hexToBytes(hex) {
  const out = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i << 1, 2), 16);
  return out;
}
function bytesToHex(b) {
  let s = ''; for (let i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, '0');
  return s;
}
function b64ToBytes(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}
function randomBytes(n) {
  const b = new Uint8Array(n);
  crypto.getRandomValues(b);
  return b;
}

// ─── Sync SHA-256 (needed for the ALTCHA PoW inner loop) ─────────────────────
// crypto.subtle.digest is async — awaiting each of ~65k iterations would take
// forever. FIPS 180-4 in plain JS runs the same batch in ~200ms which matches
// what we get from Node's crypto.createHash on the same workload.
const SHA256_K = new Uint32Array([
  0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
]);
const SHA256_H0 = new Uint32Array([
  0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,
  0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19
]);
const _rotr = (x, n) => (x >>> n) | (x << (32 - n));
function sha256(msg) {
  const L = msg.length;
  const padLen = ((L + 9 + 63) & ~63);
  const padded = new Uint8Array(padLen);
  padded.set(msg);
  padded[L] = 0x80;
  const bitLen = L * 8;
  padded[padLen - 4] = (bitLen >>> 24) & 0xFF;
  padded[padLen - 3] = (bitLen >>> 16) & 0xFF;
  padded[padLen - 2] = (bitLen >>> 8) & 0xFF;
  padded[padLen - 1] = bitLen & 0xFF;
  const H = new Uint32Array(SHA256_H0);
  const W = new Uint32Array(64);
  for (let block = 0; block < padded.length; block += 64) {
    for (let i = 0; i < 16; i++) {
      W[i] = (padded[block + i * 4] << 24) | (padded[block + i * 4 + 1] << 16)
           | (padded[block + i * 4 + 2] << 8) | padded[block + i * 4 + 3];
    }
    for (let i = 16; i < 64; i++) {
      const s0 = _rotr(W[i - 15], 7) ^ _rotr(W[i - 15], 18) ^ (W[i - 15] >>> 3);
      const s1 = _rotr(W[i - 2], 17) ^ _rotr(W[i - 2], 19) ^ (W[i - 2] >>> 10);
      W[i] = (W[i - 16] + s0 + W[i - 7] + s1) >>> 0;
    }
    let a = H[0], b = H[1], c = H[2], d = H[3], e = H[4], f = H[5], g = H[6], h = H[7];
    for (let i = 0; i < 64; i++) {
      const S1 = _rotr(e, 6) ^ _rotr(e, 11) ^ _rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (h + S1 + ch + SHA256_K[i] + W[i]) >>> 0;
      const S0 = _rotr(a, 2) ^ _rotr(a, 13) ^ _rotr(a, 22);
      const mj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + mj) >>> 0;
      h = g; g = f; f = e; e = (d + t1) >>> 0;
      d = c; c = b; b = a; a = (t1 + t2) >>> 0;
    }
    H[0] = (H[0] + a) >>> 0; H[1] = (H[1] + b) >>> 0; H[2] = (H[2] + c) >>> 0; H[3] = (H[3] + d) >>> 0;
    H[4] = (H[4] + e) >>> 0; H[5] = (H[5] + f) >>> 0; H[6] = (H[6] + g) >>> 0; H[7] = (H[7] + h) >>> 0;
  }
  const out = new Uint8Array(32);
  for (let i = 0; i < 8; i++) {
    out[i * 4] = (H[i] >>> 24) & 0xFF;
    out[i * 4 + 1] = (H[i] >>> 16) & 0xFF;
    out[i * 4 + 2] = (H[i] >>> 8) & 0xFF;
    out[i * 4 + 3] = H[i] & 0xFF;
  }
  return out;
}
function sha256Hex(str) {
  return bytesToHex(sha256(new TextEncoder().encode(str)));
}

// ─── WASM binaries embedded as base64 (makima=14KB, flicky=10KB) ─────────────
const MAKIMA_WASM_B64 = "AGFzbQEAAAABZg1gAX8Bf2ACf38Bf2ADf39/AGACf38AYAAAYAF/AGAEf39/fwBgBX9/f39/AX9gA39/fgBgA39/fwF/YAABf2AVf39/f39/f39/f39/f39/f39/f39/AX9gCn9/f39/f39/f38BfwINAQNlbnYFYWJvcnQABgM4NwIBAAEEAAIFAQEAAQACAAMDAAUFAAcCAQABAAQIBAMDAgAFAwUBCQYDBAEKAQMCAAELAAwEAgQFAwEAAQZKDn8BQcAIC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQaygAgsHQggFX2dNTHcAMwVfNnZCNwA3BV9HMDN3ADYFX3hIcUUAMQVfYVl1cgA0BV9obWtiADIFX1ZYaTQANQZtZW1vcnkCAAgBKgwBNwrOWzdNACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGyAUEtEAAACyMNIAA2AgAgACgCBCABaiACOgAAIw1BBGokDQtLACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGnAUEtEAAACyMNIAA2AgAgACgCBCABai0AACMNQQRqJA0LJQAjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIIIw1BBGokDQtDACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAAQGSABTQRAQaALQaAfQc4AQSkQAAALIAAgAUECdGooAgAjDUEEaiQNCxoAIw1BrCBIBEBBwKACQfCgAkEBQQEQAAALCz4BAX8jDUEIayQNEAUjDUIANwMAIw1BDEEEEAwiATYCACMNIAE2AgQjDSABIAAQLSIANgIAIw1BCGokDSAAC0wAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgABAZIAFNBEBBoAtBoB9B3QBBKRAAAAsjDSAANgIAIAAgAUECdGogAjYCACMNQQRqJA0LIwAgAEUEQA8LIABBFGsiABANIwhGBEAgABATIwRBAWokBAsLUQECfyMNQQhrJA0QBSMNQgA3AwAjDSABEAYiAzYCAANAIAEgAkoEQCMNIAM2AgQgAyACIAAgAmotAAAQASACQQFqIQIMAQsLIw1BCGokDSADC0sAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgASAAKAIMTwRAQaALQdAdQfIAQSoQAAALIw0gADYCACAAKAIEIAFqLQAAIw1BBGokDQsKACAAKAIEQXxxC6MBAQF/IABB7P///wNPBEBB4AlBoApBhQJBHxAAAAsjASMCTwRAAkBBgBAhAgNAIAIQLGshAiMDRQRAIwFBAXRBgAhqJAIMAgsgAkEASg0ACyMBIwEjAmtBgAhJQQp0aiQCCwsjCkUEQBAcCyMKIABBEGoQKyICIAE2AgwgAiAANgIQIAIjCSMIECEgAhAiIwFqJAEgAkEUaiIBQQAgAPwLACABCwoAIAAoAgRBA3ELSAEBfyABRQRADwsgAUEUayIBEA0jCEYEQCAAQRRrIgAQDSIDIwhFRgRAIAAgASACGxATBSMDQQFGIANBA0ZxBEAgARATCwsLC0QAIw1BBGskDRAFIw1BADYCACAAQf////8ASwRAQfAIQaAfQTNBPBAAAAsjDSAAQQJ0QQkQDCIANgIAIw1BBGokDSAAC8MBAQR/IAEoAgBBfHEiA0GAAkkEfyADQQR2BUEfQfz///8DIAMgA0H8////A08bIgNnayIEQQdrIQIgAyAEQQRrdkEQcwshBCABKAIIIQUgASgCBCIDBEAgAyAFNgIICyAFBEAgBSADNgIECyABIAAgAkEEdCAEakECdGoiASgCYEYEQCABIAU2AmAgBUUEQCAAIAJBAnRqIgEoAgRBfiAEd3EhAyABIAM2AgQgA0UEQCAAIAAoAgBBfiACd3E2AgALCwsLvAIBBX8gASgCACEDIAFBBGogASgCAEF8cWoiBCgCACICQQFxBEAgACAEEBAgASADQQRqIAJBfHFqIgM2AgAgAUEEaiABKAIAQXxxaiIEKAIAIQILIANBAnEEQCABQQRrKAIAIgEoAgAhBiAAIAEQECABIAZBBGogA0F8cWoiAzYCAAsgBCACQQJyNgIAIARBBGsgATYCACAAIANBfHEiAkGAAkkEfyACQQR2BUEfQfz///8DIAIgAkH8////A08bIgJnayIDQQdrIQUgAiADQQRrdkEQcwsiAiAFQQR0akECdGooAmAhAyABQQA2AgQgASADNgIIIAMEQCADIAE2AgQLIAAgBUEEdCACakECdGogATYCYCAAIAAoAgBBASAFdHI2AgAgACAFQQJ0aiIAIAAoAgRBASACdHI2AgQLEgAgACAANgIEIAAgADYCCCAAC4YBAQJ/IAAjBkYEQCAAKAIIJAYLAkAgABALIgFFBEAgACgCCBoMAQsgASAAKAIIIgI2AgggAiABEB8LIwchASAAKAIMIgJBAk0Ef0EBBSACQYAgKAIASwRAQaALQeALQRVBHBAAAAsgAkECdEGEIGooAgBBIHELIQIgACABIwhFQQIgAhsQIQvSAQEDfwJAAkACQAJAAkACQAJAAkACQCAAQQhrKAIADgoAAQIDBAUICAgGBwsPCw8LDwsgABAjDwsgABAjDwsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIEIQEjDSAANgIAIAEgACgCDEECdGohAgNAIAEgAkkEQCABKAIAIgMEQCADEAgLIAFBBGohAQwBCwsjDSAANgIAIAAoAgAQCCMNQQRqJA0PCw8LAAsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIAEAgjDUEEaiQNC5UFAgZ/AX4jDUEUayQNEAUjDUEAQRT8CwAjDUEIEA8iATYCACMNIAE2AgQgAUEAQefMp9AGEAcjDSABNgIEIAFBAUGF3Z7bexAHIw0gATYCBCABQQJB8ua74wMQByMNIAE2AgQgAUEDQbrqv6p6EAcjDSABNgIEIAFBBEH/pLmIBRAHIw0gATYCBCABQQVBjNGV2HkQByMNIAE2AgQgAUEGQauzj/wBEAcjDSABNgIEIAFBB0GZmoPfBRAHIw0gADYCBCAAEAOsQgOGIQcjDSAANgIEIAAQA0HAAG9BOEgEfyMNIAA2AgRBwAAgABADQcAAb2sFIw0gADYCBEGAASAAEANBwABvawshBiMNIAA2AgQjDSAAEAMgBmoQBiIGNgIIA0AjDSAANgIEIAAQAyADSgRAIw0gBjYCBCMNIAA2AgwgBiADIAAgAxACEAEgA0EBaiEDDAELCyMNIAY2AgQjDSAANgIMIAYgABADQYABEAEDQCAEQQhIBEAjDSAGNgIEIw0gBjYCDCAGIAYQA0EBayAEayAHIARBA3SsiKdB/wFxEAEgBEEBaiEEDAELCwNAIw0gBjYCBCAGEAMgBUoEQCMNIAE2AgQjDSAGNgIMIAEgBiAFEC8gBUFAayEFDAELCyMNQSAQBiIANgIQA0AgAkEISARAIw0gADYCBCMNIAE2AgwgACACQQJ0IgMgASACEARBGHYQASMNIAA2AgQjDSABNgIMIAAgA0EBaiABIAIQBEEQdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0ECaiABIAIQBEEIdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0EDaiABIAIQBEH/AXEQASACQQFqIQIMAQsLIw1BFGokDSAAC9cHAgt/A34jDUE8ayQNEAUjDUEAQTz8CwAjDSABNgIAAkACQCABEANBDEcNACMNIAM2AgAgAxADQRBHDQAjDSAANgIAIw0gABAwIgg2AgQjDUEQEAYiADYCCCMNQRAQBiIONgIMIw0gCDYCACMNIAA2AhAjDSAONgIUIAggACAOEBcjDUEQEAYiDzYCGANAIAVBDEgEQCMNIA82AgAjDSABNgIQIA8gBSABIAUQAhABIAVBAWohBQwBCwsjDSAPNgIAIA9BD0EBEAEjDUEQEAYiADYCHCMNIAA2AgAjDSAONgIQIw0gBDYCFCMNIAQ2AiAgACAOIAQgBBADECgjDSAANgIAIw0gDjYCECMNIAI2AhQjDSACNgIgIAAgDiACIAIQAxAoIw1BEBAGIgE2AiQjDSAENgIAIAQQA6xCA4YhECMNIAI2AgAgAhADrEIDhiERA0AgCUEISARAIw0gATYCACABQQcgCWsgECAJQQN0rCISiKdB/wFxEAEjDSABNgIAIAFBDyAJayARIBKIp0H/AXEQASAJQQFqIQkMAQsLA0AgCkEQSARAIw0gADYCACMNIAA2AhAgACAKEAIhBCMNIAE2AhAgACAKIAEgChACIARzEAEgCkEBaiEKDAELCyMNIAA2AgAjDSAONgIQIAAgDhApIw1BEBAGIgE2AigjDSAINgIAIw0gDzYCECMNIAE2AhQgCCAPIAEQFyMNQRAQBiIENgIsA0AgC0EQSARAIw0gBDYCACMNIAA2AhAgACALEAIhBSMNIAE2AhAgBCALIAEgCxACIAVzQf8BcRABIAtBAWohCwwBCwsDQCAGQRBIBEAjDSAENgIAIAQgBhACIQAjDSADNgIAIAcgAyAGEAIgAHNyIQcgBkEBaiEGDAELCyAHQf8BcQ0AIw0gAjYCACMNIAIQAxAGIgA2AjAjDUEQEAYiAzYCNANAIA1BEEgEQCMNIAM2AgAjDSAPNgIQIAMgDSAPIA0QAhABIA1BAWohDQwBCwsjDSADNgIAIAMQJSMNQRAQBiIENgI4A0AjDSACNgIAIAIQAyAMSgRAIw0gCDYCACMNIAM2AhAjDSAENgIUIAggAyAEEBcjDSACNgIAIAIQAyAMa0EQTgR/QRAFIw0gAjYCACACEAMgDGsLIQVBACEBA0AgASAFSARAIw0gADYCACMNIAI2AhAgAiABIAxqIgYQAiEHIw0gBDYCECAAIAYgBCABEAIgB3NB/wFxEAEgAUEBaiEBDAELCyAMQRBqIQwjDSADNgIAIAMQJQwBCwsMAQtBACEACyMNQTxqJA0gAAviCQEMfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgM2AgADQCAEQRBIBEAjDSADNgIEIw0gATYCCCADIAQgASAEEAIQASAEQQFqIQQMAQsLQQAhAQNAIAFBBEgEQCMNIAA2AgQgACABEAQhBCMNIAM2AgQjDSADNgIIIAMgAUECdCIFIAMgBRACIARBGHZzEAEjDSADNgIEIw0gAzYCCCADIAVBAWoiBiADIAYQAiAEQRB2cxABIw0gAzYCBCMNIAM2AgggAyAFQQJqIgYgAyAGEAIgBEEIdnMQASMNIAM2AgQjDSADNgIIIAMgBUEDaiIFIAMgBRACIARzEAEgAUEBaiEBDAELC0EBIQQDQCAEQQ5MBEBBACEBA0AgAUEQSARAIw0gAzYCBCMNQdAcNgIIIw0gAzYCDCADIAFB0BwgAyABEAIQChABIAFBAWohAQwBCwsjDSADNgIEIANBARACIQEjDSADNgIEIw0gAzYCCCADQQEgA0EFEAIQASMNIAM2AgQjDSADNgIIIANBBSADQQkQAhABIw0gAzYCBCMNIAM2AgggA0EJIANBDRACEAEjDSADNgIEIANBDSABEAEjDSADNgIEIANBAhACIQEjDSADNgIEIANBBhACIQUjDSADNgIEIw0gAzYCCCADQQIgA0EKEAIQASMNIAM2AgQjDSADNgIIIANBBiADQQ4QAhABIw0gAzYCBCADQQogARABIw0gAzYCBCADQQ4gBRABIw0gAzYCBCADQQ8QAiEBIw0gAzYCBCMNIAM2AgggA0EPIANBCxACEAEjDSADNgIEIw0gAzYCCCADQQsgA0EHEAIQASMNIAM2AgQjDSADNgIIIANBByADQQMQAhABIw0gAzYCBCADQQMgARABIARBDkgEQEEAIQEDQCABQQRIBEAjDSADNgIEIAMgAUECdCIIEAIhCyMNIAM2AgQgAyAIQQFqIgUQAiEMIw0gAzYCBCADIAhBAmoiBhACIQkjDSADNgIEIAMgCEEDaiIHEAIiCiALIAxzIg0gCXNzIQ4jDSADNgIEIAMgCCANQf8BcUEHdkEbbCANQQF0c0H/AXEgCyAOc3NB/wFxEAEjDSADNgIEIAMgBSAJIAxzIgVB/wFxQQd2QRtsIAVBAXRzQf8BcSAMIA5zc0H/AXEQASMNIAM2AgQgAyAGIAkgCnMiBUH/AXFBB3ZBG2wgBUEBdHNB/wFxIAkgDnNzQf8BcRABIw0gAzYCBCADIAcgCiALcyIFQf8BcUEHdkEbbCAFQQF0c0H/AXEgCiAOc3NB/wFxEAEgAUEBaiEBDAELCwtBACEBA0AgAUEESARAIw0gADYCBCAAIARBAnQgAWoQBCEFIw0gAzYCBCMNIAM2AgggAyABQQJ0IgYgAyAGEAIgBUEYdnMQASMNIAM2AgQjDSADNgIIIAMgBkEBaiIHIAMgBxACIAVBEHZzEAEjDSADNgIEIw0gAzYCCCADIAZBAmoiByADIAcQAiAFQQh2cxABIw0gAzYCBCMNIAM2AgggAyAGQQNqIgYgAyAGEAIgBXMQASABQQFqIQEMAQsLIARBAWohBAwBCwtBACEAA0AgAEEQSARAIw0gAjYCBCMNIAM2AgggAiAAIAMgABACEAEgAEEBaiEADAELCyMNQRBqJA0LPwAjDUEEayQNEAUjDUEANgIAIw0gADYCACABIABBFGsoAhBBAXZPBH9BfwUgACABQQF0ai8BAAsjDUEEaiQNCw0AIABBFGsoAhBBAnYLjgEBAn8gAUGAAkkEfyABQQR2BUEfIAEQGyIBZ2siA0EHayECIAEgA0EEa3ZBEHMLIQEgACACQQJ0aigCBEF/IAF0cSIBBH8gACABaCACQQR0akECdGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAAgACABaCIAQQJ0aigCBGggAEEEdGpBAnRqKAJgBUEACwsLHQAgAEEBQRsgAGdrdGpBAWsgACAAQf7///8BSRsLlwEBAn8/ACIAQQBMBH9BASAAa0AAQQBIBUEACwRAAAtBsKACQQA2AgBB0KwCQQA2AgADQCABQRdJBEAgAUECdEGwoAJqQQA2AgRBACEAA0AgAEEQSQRAIAFBBHQgAGpBAnRBsKACakEANgJgIABBAWohAAwBCwsgAUEBaiEBDAELC0GwoAJB1KwCPwCsQhCGEB1BsKACJAoLhgEBA38gAUETakFwcUEEayEBIAAoAqAMIgMEQCABQRBrIgUgA0YEQCADKAIAIQQgBSEBCwsgAqdBcHEgAWsiA0EUSQRADwsgASAEQQJxIANBCGsiA0EBcnI2AgAgAUEANgIEIAFBADYCCCABQQRqIANqIgNBAjYCACAAIAM2AqAMIAAgARARC24BAn8jACIABEAgABAICyMLIgAEQCAAEAgLQZAREAhB4BIQCEGwFxAIQYAaEAhB0BwQCEGgHRAIQaALEAhB8AgQCEHgCRAIIwUiARALIQADQCAAIAFHBEAgABANGiAAQRRqEBQgABALIQAMAQsLCxIAIAAgASAAKAIEQQNxcjYCBAsSACAAIAAoAgRBfHEgAXI2AgQLKQEBfyABKAIIIQMgACABIAJyNgIEIAAgAzYCCCADIAAQHyABIAA2AggLDQAgACgCAEF8cUEEagsJACAAKAIAEAgLEQAgACABNgIAIAAgAUEAEA4LZgEBfyMNQQhrJA0QBSMNQgA3AwBBDyEBA0AgAUEMTgRAAkAjDSAANgIAIw0gADYCBCAAIAEgACABEAJBAWpB/wFxEAEjDSAANgIAIAAgARACDQAgAUEBayEBDAILCwsjDUEIaiQNC9wEAQd/Iw1BJGskDRAFIw1BAEEk/AsAIw0gADYCACMNIAA2AgQgABADQcAASgRAIw0gADYCBCMNIAAQFSIANgIACyMNQcAAEAYiCDYCCANAIw0gADYCBCAAEAMgAkoEQCMNIAg2AgQjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsjDUHAABAGIgA2AhAjDUHAABAGIgI2AhQDQCADQcAASARAIw0gADYCBCMNIAg2AgwgACADIAggAxACQdwAc0H/AXEQASMNIAI2AgQjDSAINgIMIAIgAyAIIAMQAkE2c0H/AXEQASADQQFqIQMMAQsLIw0gAjYCBCMNIAIQAyEIIw0gATYCBCABEAMgCGoQBiIDNgIYA0AjDSACNgIEIAIQAyAESgRAIw0gAzYCBCMNIAI2AgwgAyAEIAIgBBACEAEgBEEBaiEEDAELCwNAIw0gATYCBCABEAMgBUoEQCMNIAM2AgQjDSACNgIMIAIQAyAFaiEEIw0gATYCDCADIAQgASAFEAIQASAFQQFqIQUMAQsLIw0gAzYCBCMNIAMQFSIBNgIcIw0gADYCBCMNIAAQAyEDIw0gATYCBCABEAMgA2oQBiICNgIgA0AjDSAANgIEIAAQAyAGSgRAIw0gAjYCBCMNIAA2AgwgAiAGIAAgBhACEAEgBkEBaiEGDAELCwNAIw0gATYCBCABEAMgB0oEQCMNIAI2AgQjDSAANgIMIAAQAyAHaiEDIw0gATYCDCACIAMgASAHEAIQASAHQQFqIQcMAQsLIw0gAjYCBCACEBUjDUEkaiQNC6IDAQZ/Iw1BGGskDRAFIw1BAEEY/AsAIw0gATYCACMNIAA2AgQjDSABIAAQJiIGNgIIIw1BIBAGIgQ2AgwjDUEAEAYiADYCEEEBIQUDQCADQSBIBEAjDSAANgIAIw0gABADIQcjDSACNgIAIAIQAyAHakEBahAGIgc2AhRBACEBA0AjDSAANgIAIAAQAyABSgRAIw0gBzYCACMNIAA2AgQgByABIAAgARACEAEgAUEBaiEBDAELC0EAIQEDQCMNIAI2AgAgAhADIAFKBEAjDSAHNgIAIw0gADYCBCAAEAMgAWohCCMNIAI2AgQgByAIIAIgARACEAEgAUEBaiEBDAELCyMNIAc2AgAjDSAHNgIEIAcgBxADQQFrIAVB/wFxEAEjDSAGNgIAIw0gBzYCBCMNIAYgBxAmIgA2AhAjDSAANgIAIAAQA7dBICADa7ek/AIhB0EAIQEDQCABIAdIBEAjDSAENgIAIw0gADYCBCAEIAEgA2ogACABEAIQASABQQFqIQEMAQsLIAMgB2ohAyAFQQFqIQUMAQsLIw1BGGokDSAEC5sBAQR/Iw1BCGskDRAFIw1CADcDAANAIAMgBUoEQEEQIAMgBWsiBCAEQRBOGyEGQQAhBANAIAQgBkgEQCMNIAA2AgAjDSAANgIEIAAgBBACIQcjDSACNgIEIAAgBCACIAQgBWoQAiAHcxABIARBAWohBAwBCwsjDSAANgIAIw0gATYCBCAAIAEQKSAFQRBqIQUMAQsLIw1BCGokDQuHAwEHfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgc2AgAjDUEQEAYiCDYCBANAIAJBEEgEQCMNIAg2AggjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsDQCAFQYABSARAIw0gATYCCCABIAVBA3YQAkEHIAVBB3FrQQdxdkEBcQRAQQAhAgNAIAJBEEgEQCMNIAc2AggjDSAHNgIMIAcgAhACIQMjDSAINgIMIAcgAiAIIAIQAiADcxABIAJBAWohAgwBCwsLQQAhAkEAIQYDQCAGQRBIBEAjDSAINgIIIAggBhACQQFxIw0gCDYCCCMNIAg2AgwgCCAGIAJBB3QgCCAGEAJBAXZyQf8BcRABIQIgBkEBaiEGDAELCyACBEAjDSAINgIIIw0gCDYCDCAIQQAgCEEAEAJB4QFzEAELIAVBAWohBQwBCwsDQCAEQRBIBEAjDSAANgIIIw0gBzYCDCAAIAQgByAEEAIQASAEQQFqIQQMAQsLIw1BEGokDQssAD8AQRB0QaygAmtBAXYkAkHQChASJAVB8AoQEiQHQYAMEBIkCUEAEAYkCwuTAgEDfyABQfz///8DSwRAQeAJQbAMQc0DQR0QAAALIABBDCABQRNqQXBxQQRrIAFBDE0bIgMQGiIBRQRAQQQgACgCoAw/ACIBQRB0QQRrR3QgAxAbIAMgA0GAAk8bakH//wNqQYCAfHFBEHYhAiABIAIgASACShtAAEEASARAIAJAAEEASARAAAsLIAAgAUEQdD8ArEIQhhAdIAAgAxAaIQELIAEoAgAaIAAgARAQIAEoAgAiAkF8cSADayIEQRBPBEAgASADIAJBAnFyNgIAIAFBBGogA2oiAiAEQQRrQQFyNgIAIAAgAhARBSABIAJBfnE2AgAgAUEEaiABKAIAQXxxaiIAIAAoAgBBfXE2AgALIAEL/wIBAn8CQAJAAkACQCMDDgMAAQIDC0EBJANBACQEEB4jByQGIwQPCyMIRSEBIwYQCyEAA0AgACMHRwRAIAAkBiAAEA0gAUcEQCAAIAEQIEEAJAQgAEEUahAUIwQPCyAAEAshAAwBCwtBACQEEB4jBhALIwdGBEAjDSEAA0AgAEGsoAJJBEAgACgCABAIIABBBGohAAwBCwsjBhALIQADQCAAIwdHBEAgABANIAFHBEAgACABECAgAEEUahAUCyAAEAshAAwBCwsjCSEAIwckCSAAJAcgASQIIAAQCyQGQQIkAwsjBA8LIwYiACMHRwRAIAAQCyQGIAAQDRogAEGsoAJJBEAgAEEANgIEIABBADYCCAUjASAAECJrJAEgAEEEaiIAQaygAk8EQCMKRQRAEBwLIABBBGshASAAQQ9xQQEgABsEf0EBBSABKAIAQQFxCxogASABKAIAQQFyNgIAIwogARARCwtBCg8LIwcjBzYCBCMHIwc2AghBACQDC0EAC7YBAQF/Iw1BEGskDRAFIw1CADcDACMNQgA3AwggAEUEQCMNQQxBAxAMIgA2AgALIw0gADYCBCAAQQAQJCMNIAA2AgQgAEEANgIEIw0gADYCBCAAQQA2AgggAUH8////A0sEQEHwCEGgCUETQTkQAAALIw0gAUEBEAwiAjYCCCMNIAA2AgQjDSACNgIMIAAgAhAkIw0gADYCBCAAIAI2AgQjDSAANgIEIAAgATYCCCMNQRBqJA0gAAvwAQEDfyMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCCICQQJ2SwRAIAFB/////wBLBEBB8AhB0B1BE0EwEAAACyMNIAA2AgACQEH8////AyACQQF0IgIgAkH8////A08bIgJBCCABIAFBCE0bQQJ0IgEgASACSRsiAyAAKAIAIgJBFGsiBCgCAEF8cUEQa00EQCAEIAM2AhAgAiEBDAELIAMgBCgCDBAMIgEgAiADIAQoAhAiBCADIARJG/wKAAALIAEgAkcEQCAAIAE2AgAgACABNgIEIAAgAUEAEA4LIAAgAzYCCAsjDUEEaiQNC/8HAQp/Iw1BDGskDRAFIw1CADcDACMNQQA2AggjDUHAABAPIgw2AgADQCAEQRBIBEAjDSAMNgIEIw0gATYCCCABIAIgBEECdGoiBRACQRh0Iw0gATYCCCABIAVBAWoQAkEQdHIjDSABNgIIIAEgBUECahACQQh0ciEDIw0gATYCCCAMIAQgASAFQQNqEAIgA3IQByAEQQFqIQQMAQsLQRAhBANAIARBwABIBEAjDSAMNgIEIAwgBEEPayIDEAQhAiMNIAw2AgQgDCADEAQhASMNIAw2AgQgAkEZdCACQQd2ciABQQ50IAFBEnZycyAMIAMQBEEDdnMhBSMNIAw2AgQgDCAEQQJrIgMQBCECIw0gDDYCBCAMIAMQBCEBIw0gDDYCBCACQQ90IAJBEXZyIAFBDXQgAUETdnJzIAwgAxAEQQp2cyECIw0gDDYCBCMNIAw2AgggDCAEQRBrEAQgBWohASMNIAw2AgggDCAEIAwgBEEHaxAEIAFqIAJqEAcgBEEBaiEEDAELCyMNIAA2AgQgAEEAEAQhCCMNIAA2AgQgAEEBEAQhBCMNIAA2AgQgAEECEAQhAyMNIAA2AgQgAEEDEAQhBiMNIAA2AgQgAEEEEAQhByMNIAA2AgQgAEEFEAQhAiMNIAA2AgQgAEEGEAQhASMNIAA2AgQgAEEHEAQhBQNAIAtBwABIBEAjDUGAGjYCBCMNQQRrJA0QBSMNQQA2AgAjDUGAGjYCACALQYwaKAIATwRAQaALQdAdQfIAQSoQAAALIw1BgBo2AgBBhBooAgAgC0ECdGooAgAhCSMNQQRqJA0jDSAMNgIEIAwgCxAEIAdBB3QgB0EZdnIgB0EadCAHQQZ2ciAHQRV0IAdBC3Zyc3MgBWogAiAHcSAHQX9zIAFxc2ogCWpqIQogCEEKdCAIQRZ2ciAIQR50IAhBAnZyIAhBE3QgCEENdnJzcyADIARxIAQgCHEgAyAIcXNzaiABIQUgAiEBIAchAiAGIApqIQcgAyEGIAQhAyAIIQQgCmohCCALQQFqIQsMAQsLIw0gADYCBCMNIAA2AgggAEEAIABBABAEIAhqEAcjDSAANgIEIw0gADYCCCAAQQEgAEEBEAQgBGoQByMNIAA2AgQjDSAANgIIIABBAiAAQQIQBCADahAHIw0gADYCBCMNIAA2AgggAEEDIABBAxAEIAZqEAcjDSAANgIEIw0gADYCCCAAQQQgAEEEEAQgB2oQByMNIAA2AgQjDSAANgIIIABBBSAAQQUQBCACahAHIw0gADYCBCMNIAA2AgggAEEGIABBBhAEIAFqEAcjDSAANgIEIw0gADYCCCAAQQcgAEEHEAQgBWoQByMNQQxqJA0L6AMBBH8jDUEMayQNEAUjDUIANwMAIw1BADYCCCMNQTwQDyICNgIAA0AgAUEISARAIw0gAjYCBCMNIAA2AgggACABQQJ0IgMQAkEYdCMNIAA2AgggACADQQFqEAJBEHRyIw0gADYCCCAAIANBAmoQAkEIdHIhBCMNIAA2AgggAiABIAAgA0EDahACIARyEAcgAUEBaiEBDAELC0EIIQADQCAAQTxIBEAjDSACNgIEIAIgAEEBaxAEIQEgAEEHcQR/IABBCG9BBEYEfyMNQdAcNgIEQdAcIAFBGHYQCkEYdCMNQdAcNgIEQdAcIAFBEHZB/wFxEApBEHRyIw1B0Bw2AgRB0BwgAUEIdkH/AXEQCkEIdHIhAyMNQdAcNgIEQdAcIAFB/wFxEAogA3IFIAELBSMNQdAcNgIEQdAcIAFBCHQgAUEYdnIiAUEYdhAKQRh0Iw1B0Bw2AgRB0BwgAUEQdkH/AXEQCkEQdHIjDUHQHDYCBEHQHCABQQh2Qf8BcRAKQQh0ciEDIw1B0Bw2AgRB0BwgAUH/AXEQCiADciMNQaAdNgIEQaAdIABBCG0QCkEYdHMLIQEjDSACNgIEIw0gAjYCCCACIAAgAiAAQQhrEAQgAXMQByAAQQFqIQAMAQsLIw1BDGokDSACCwoAIAAgAWotAAALmwYBCH8jDUHYAGskDRAFIw1BAEHYAPwLAAJ/AkAjDEUNACMNIAAgARAJIgE2AgAjDSACIAMQCSICNgIEIw0gBCAFEAkiAzYCCCMNIAYgBxAJIgQ2AgwjDSAIIAkQCSIFNgIQIw0gCiALEAkiBjYCFCMNIAwgDRAJIgc2AhgjDSAOIA8QCSIINgIcIw0gECAREAkiCTYCICMNIBIgExAJIgo2AiQjDSABNgIoIw0gARADIQsjDSACNgIoIAIQAyALaiELIw0gAzYCKCADEAMgC2oQBiILNgIsA0AjDSABNgIoIAEQAyAYSgRAIw0gCzYCKCAVIgBBAWohFSMNIAE2AjAgCyAAIAEgGBACEAEgGEEBaiEYDAELCwNAIw0gAjYCKCACEAMgGUoEQCMNIAs2AiggFSIAQQFqIRUjDSACNgIwIAsgACACIBkQAhABIBlBAWohGQwBCwsDQCMNIAM2AiggAxADIBpKBEAjDSALNgIoIBUiAEEBaiEVIw0gAzYCMCALIAAgAyAaEAIQASAaQQFqIRoMAQsLIw1BDhAGIgA2AjQDQCAWQQ5IBEAjDSAANgIoIAAgFkHgHyAWEBhB/wFxEAEgFkEBaiEWDAELCyMNIwsiATYCKCMNIAs2AjAjDSAANgI4Iw0gASALIAAQJyIANgI8Iw0gADYCKCMNIAU2AjAjDSAGNgI4Iw0gBzYCQCMNIAQ2AkQjDSAAIAUgBiAHIAQQFiIBNgJIA0AjDSAANgIoIAAQAyAbSgRAIw0gADYCKCAAIBtBABABIBtBAWohGwwBCwsgAUUNACMNIAE2AigjDSAINgIwIw0gCTYCOCMNIAo2AkAjDSAENgJEIw0gASAIIAkgCiAEEBYiADYCTCMNIAE2AlADQCMNIAE2AiggARADIBxKBEAjDSABNgIoIAEgHEEAEAEgHEEBaiEcDAELCyAARQ0AIw0gADYCVANAIw0gADYCKCAAEAMgF0oEQCMNIAA2AiggFCAXaiAAIBcQAjoAACAXQQFqIRcMAQsLIw0gADYCKCAAEAMMAQtBfwsjDUHYAGokDQukAQEDfyMNQQxrJA0QBSMNQgA3AwAjDUEANgIIIw0gABAGIgM2AgAjDSMAIgI2AgQjDSADNgIIIw1BBGskDRAFIw1BADYCACMNIAI2AgAgAiACKAIMIgBBAWoiARAuIw0gAjYCACACKAIEIABBAnRqIAM2AgAgAiADQQEQDiMNIAI2AgAgAiABNgIMIw1BBGokDSMNIAM2AgQgAygCBCMNQQxqJA0LzwUAIw1BPGskDRAFIw1BAEE8/AsAIw0gACABEAkiATYCACMNIAIgAxAJIgI2AgQjDSAEIAUQCSIDNgIIIw0gBiAHEAkiBTYCDCMNIAggCRAJIgY2AhAjDUGAARAGIgc2AhRBACEAA0AgAEGAAUgEQCMNIAc2AhgjDUGQETYCHCMNQbAXNgIgIw1BBGskDRAFIw1BADYCACMNQbAXNgIAIABBvBcoAgBPBEBBoAtB0B1B8gBBKhAAAAsjDUGwFzYCAEG0FygCACAAQQJ0aigCACEEIw1BBGokDUGQESAEEAohBCMNQeASNgIcIAcgAEHgEiAAEAogBHNB/wFxEAEgAEEBaiEADAELCyMNIAE2AhgjDSABEAMhBCMNIAI2AhggAhADIARqEAYiADYCJEEAIQQDQCMNIAE2AhggARADIARKBEAjDSAANgIYIw0gATYCHCAAIAQgASAEEAIQASAEQQFqIQQMAQsLQQAhBANAIw0gAjYCGCACEAMgBEoEQCMNIAA2AhgjDSABNgIcIAEQAyAEaiEIIw0gAjYCHCAAIAggAiAEEAIQASAEQQFqIQQMAQsLIw1BFRAGIgQ2AihBACECA0AgAkEVSARAIw0gBDYCGCAEIAJB4B4gAhAYQf8BcRABIAJBAWohAgwBCwsjDSAHNgIYIw0gADYCHCMNIAQ2AiAjDSAHIAAgBBAnIgA2AixBACECA0AgAkGAAUgEQCMNIAc2AhggByACQQAQASACQQFqIQIMAQsLIw0gADYCGCMNIAM2AhwjDSAFNgIgIw0gBjYCMCMNIAE2AjQjDSAAIAMgBSAGIAEQFiICNgI4QQAhAQNAIw0gADYCGCAAEAMgAUoEQCMNIAA2AhggACABQQAQASABQQFqIQEMAQsLIAJFBEBBACQMIw1BPGokDUF/DwsgAiQLQQEkDCMNIwsiADYCGCAAEAMjDUE8aiQNC1UBAn8jDUEEayQNEAUjDUEANgIAA0AjDSMLIgE2AgAgARADIABKBEAjDSMLIgE2AgAgASAAQQAQASAAQQFqIQAMAQsLQQAQBiQLQQAkDCMNQQRqJA0LDAAgACABaiACOgAAC2EBAn8jDUEEayQNEAUjDUEANgIAIw1BAEEBEAwiAEGAHkEA/AoAACAANgIAQRBBBRAMIgEgADYCACABIABBABAOIAEgADYCBCABQQA2AgggAUEANgIMIw1BBGokDSABJAALC78VNwBBjAgLARwAQZgICwEBAEGsCAsBLABBuAgLDgUAAAAQAAAAIAQAACAEAEHcCAsBLABB6AgLIwIAAAAcAAAASQBuAHYAYQBsAGkAZAAgAGwAZQBuAGcAdABoAEGMCQsBPABBmAkLLQIAAAAmAAAAfgBsAGkAYgAvAGEAcgByAGEAeQBiAHUAZgBmAGUAcgAuAHQAcwBBzAkLATwAQdgJCy8CAAAAKAAAAEEAbABsAG8AYwBhAHQAaQBvAG4AIAB0AG8AbwAgAGwAYQByAGcAZQBBjAoLATwAQZgKCycCAAAAIAAAAH4AbABpAGIALwByAHQALwBpAHQAYwBtAHMALgB0AHMAQYwLCwE8AEGYCwsrAgAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQBBzAsLASwAQdgLCxsCAAAAFAAAAH4AbABpAGIALwByAHQALgB0AHMAQZwMCwE8AEGoDAslAgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcwBB3AwLAhwCAEHoDAuIBAEAAAAAAgAA3GSMMqWXv7Kn+4yrVKE4h2ZdlzA6Tf9X12bKKX1AmvUA5SC0Bk2S+2z+ZPld+c7hCePedNGIHDfKtnwYDBSi8AMPzEQoFYg5JmAwZJeeLaKk5FLjKIQOEDbXLyMum9MZn9u+TH7Y64hufagAoVky4xb4C53iYgne7HOy7r1BJNeoCmz/px+HoozSYmUlR8wBW/MiOMZ/OgrmecFUUOIKesy8sSBJ/eIkQZjOjGMmE9LMJbrOlXWkTjhko6Gt1YR3ZZOD+ZlG5jOtyzKpldhGDkUmAdqLf1iUoN2QNkFdQIyx21TcvAZr9Vg4AgMVfvHH/g21KcisB5ccZQQ/XaIN2GDrV9exRgpUMcARVM5XEAj1f6Rzkti/U8iNI56tF2qiI1+WYz+FFVP7rSTQH3voCEN1IZPNZQIWyPO/+7LdHzg7l7sqOGCQo3whGWRqU2b/vixMPBYPVVQ/cExqPo++NpGSl6SRDVm9etrii2tTPO79yci0dp3VLnkz5MejUnFjY4vjWoAbdc7ODpbt8I5VzrBMHFiB2gFlvqxEpp8iBPBGJ9IyefM75pxylAwhR3OoNLuqx6RI5BzxGAxQ42+rPXX7QEXLm97QOED8qmaxefjV2/OPY4HEsFrvJwQ9+i5ZiUFAWbxR5wx4zy7wVLm7mUXTmoi+aTxnSPxdN/BaUTkAQfwQCwEsAEGIEQsWBgAAABAAAABwBgAAcAYAAAACAAAAAgBBrBELAZwAQbgRC4gBAQAAAIAAAABWN8Rt27m56SQBSRF5bjclm/MstI3M2EWjXXEkrN5l5kN8HeGWOzq5/wf9rXWEvzyV1sczhTZZRwTkLtSGIoWlvuqc49PRzcUzQDooVQiq50ky7PCmAxDqMtbvq3vB3XDuLny0NwWuqrJci/3jG/lHL0CWqP/XSbdidynvdgIangBBzBILASwAQdgSCxUGAAAAEAAAAMAIAADACAAAgAAAAIAAQfwSCwIcAgBBiBMLhQQBAAAAAAIAADYAAADUAQAArwEAACEBAAA1AAAA4AEAAAIAAAAbAQAATgEAAK0BAABKAAAA3wEAABoBAAA9AAAAEwEAAHAAAAAxAAAAsgEAANUAAADEAAAAeAAAAJgBAABkAQAAbgAAAKYAAABcAQAA6gEAAOUBAACHAQAAqgEAAHcBAABnAAAA9gAAAD8BAAD3AQAAsQEAAC4AAAAoAAAASQAAAAkBAACiAAAAMAEAAKgBAADGAQAAIAAAAO8AAAAoAQAAlwAAALwAAAAjAAAAQQEAAIsAAACzAQAAfQAAAL0BAAD7AQAAyQEAAMwAAAAZAAAAKwAAAAEBAAB9AQAAxwEAAIoBAACBAQAARgEAAC4BAABhAAAA1wEAAIAAAADkAAAADwAAAH8BAAAxAQAACwEAAOgBAADIAQAAzgAAAI4AAABzAAAAIgAAAMIBAADNAAAA8gAAAIwBAABZAQAAQwAAAGcBAABLAQAAmwEAAJkBAADhAAAASQEAAGABAAAFAAAAxQAAAOQBAACoAAAAgQAAALgBAADlAAAAigAAAKcBAADEAQAAwwAAAHYAAACJAAAA1AAAAJQBAACZAAAAyQAAADIBAAAqAAAAGwAAAN0BAABvAAAAegAAAG8BAACdAQAAdAAAAB0BAAA7AAAA+QAAAMUBAACNAAAA+AEAAIABAACzAEGcFwsBLABBqBcLFQcAAAAQAAAAkAkAAJAJAAAAAgAAgABBzBcLAhwBAEHYFwuIAgEAAAAAAQAAmC+KQpFEN3HP+8C1pdu16VvCVjnxEfFZpII/ktVeHKuYqgfYAVuDEr6FMSTDfQxVdF2+cv6x3oCnBtybdPGbwcFpm+SGR77vxp3BD8yhDCRvLOktqoR0StypsFzaiPl2UlE+mG3GMajIJwOwx39Zv/ML4MZHkafVUWPKBmcpKRSFCrcnOCEbLvxtLE0TDThTVHMKZbsKanYuycKBhSxykqHov6JLZhqocItLwqNRbMcZ6JLRJAaZ1oU1DvRwoGoQFsGkGQhsNx5Md0gntbywNLMMHDlKqthOT8qcW/NvLmjugo90b2OleBR4yIQIAseM+v++kOtsUKT3o/m+8nhxxgBB7BkLASwAQfgZCxUIAAAAEAAAAOALAADgCwAAAAEAAEAAQZwaCwIcAQBBqBoLiAIBAAAAAAEAAGN8d3vya2/FMAFnK/7Xq3bKgsl9+llH8K3Uoq+cpHLAt/2TJjY/98w0peXxcdgxFQTHI8MYlgWaBxKA4usnsnUJgywaG25aoFI71rMp4y+EU9EA7SD8sVtqy745SkxYz9DvqvtDTTOFRfkCf1A8n6hRo0CPkp049by22iEQ//PSzQwT7F+XRBfEp349ZF0Zc2CBT9wiKpCIRu64FN5eC9vgMjoKSQYkXMLTrGKRleR558g3bY3VTqlsVvTqZXquCLp4JS4cprTG6N10H0u9i4pwPrVmSAP2DmE1V7mGwR2e4fiYEWnZjpSbHofpzlUo34yhiQ2/5kJoQZktD7BUuxYAQbwcCwEsAEHIHAsWBgAAABAAAAAwDQAAMA0AAAABAAAAAQBB7BwLARwAQfgcCxMBAAAACwAAAAABAgQIECBAgBs2AEGMHQsBLABBmB0LFQYAAAAQAAAAgA4AAIAOAAALAAAACwBBvB0LASwAQcgdCyECAAAAGgAAAH4AbABpAGIALwBhAHIAcgBhAHkALgB0AHMAQewdCwEcAEH4HQsBAQBBjB4LATwAQZgeCysCAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEHMHgsBPABB2B4LMQIAAAAqAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwAC0AcABlAHAAcABlAHIAOgB2ADEAQYwfCwE8AEGYHwstAgAAACYAAAB+AGwAaQBiAC8AcwB0AGEAdABpAGMAYQByAHIAYQB5AC4AdABzAEHMHwsBLABB2B8LIwIAAAAcAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwADoAdgAxAEGAIAsqCgAAACAAAAAgAAAAIAAAAAAAAABBAAAAAkEAAEIAAAACCQAAAgEAACQB";
const FLICKY_WASM_B64 = "AGFzbQEAAAABLwlgAn9/AX9gAX8Bf2ACf38AYAAAYAF/AGADf39/AGAAAX9gBH9/f38AYAN/f34AAg0BA2VudgVhYm9ydAAHAzEwAQMCAgQFBAQCAggDBgEAAAACAgUAAQQDBAMDAAEABQYBAQAFAAACBQEAAAABAAAABQMBAAEGRQ1/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwBB4BULfwFBjJYCCwdMBwVfX25ldwARBV9fcGluABYHX191bnBpbgAXCV9fY29sbGVjdAAYC19fcnR0aV9iYXNlAwsGbWVtb3J5AgALZGVvYmZ1c2NhdGUAMAgBGgwBMQrAPjASACAAIAA2AgQgACAANgIIIAALZgECf0HAChAIQaALEAhBgAwQCEHgDBAIQcAPEAhBkA0QCEGADhAIQfAUEAhBsBUQCEGAEhAIIwQiASgCBEF8cSEAA0AgACABRwRAIAAoAgQaIABBFGoQGSAAKAIEQXxxIQAMAQsLCxIAIAAgACgCBEF8cSABcjYCBAsSACAAIAEgACgCBEEDcXI2AgQLKwEBfyAAKAIEQXxxIgFFBEAgACgCCBoPCyABIAAoAggiADYCCCAAIAEQBAspAQF/IAEoAgghAyAAIAEgAnI2AgQgACADNgIIIAMgABAEIAEgADYCCAtjAQJ/IAAjBUYEQCAAKAIIJAULIAAQBSMGIQEgACgCDCICQQJNBH9BAQUgAkHgFSgCAEsEQEHAD0GAEEEVQRwQAAALIAJBAnRB5BVqKAIAQSBxCyECIAAgASMHRUECIAIbEAYLJwAgAEUEQA8LIwcgAEEUayIAKAIEQQNxRgRAIAAQByMDQQFqJAMLC8MBAQR/IAEoAgBBfHEiA0GAAkkEfyADQQR2BUEfQfz///8DIAMgA0H8////A08bIgNnayIEQQdrIQIgAyAEQQRrdkEQcwshAyABKAIIIQUgASgCBCIEBEAgBCAFNgIICyAFBEAgBSAENgIECyABIAAgAkEEdCADakECdGoiASgCYEYEQCABIAU2AmAgBUUEQCAAIAJBAnRqIgEoAgRBfiADd3EhAyABIAM2AgQgA0UEQCAAIAAoAgBBfiACd3E2AgALCwsLvAIBBX8gASgCACEDIAFBBGogASgCAEF8cWoiBCgCACICQQFxBEAgACAEEAkgASADQQRqIAJBfHFqIgM2AgAgAUEEaiABKAIAQXxxaiIEKAIAIQILIANBAnEEQCABQQRrKAIAIgEoAgAhBiAAIAEQCSABIAZBBGogA0F8cWoiAzYCAAsgBCACQQJyNgIAIARBBGsgATYCACAAIANBfHEiAkGAAkkEfyACQQR2BUEfQfz///8DIAIgAkH8////A08bIgJnayIDQQdrIQUgAiADQQRrdkEQcwsiAiAFQQR0akECdGooAmAhAyABQQA2AgQgASADNgIIIAMEQCADIAE2AgQLIAAgBUEEdCACakECdGogATYCYCAAIAAoAgBBASAFdHI2AgAgACAFQQJ0aiIAIAAoAgRBASACdHI2AgQLhgEBA38gAUETakFwcUEEayEBIAAoAqAMIgMEQCADIAFBEGsiBUYEQCADKAIAIQQgBSEBCwsgAqdBcHEgAWsiA0EUSQRADwsgASAEQQJxIANBCGsiA0EBcnI2AgAgAUEANgIEIAFBADYCCCABQQRqIANqIgNBAjYCACAAIAM2AqAMIAAgARAKC5cBAQJ/PwAiAUEATAR/QQEgAWtAAEEASAVBAAsEQAALQZCWAkEANgIAQbCiAkEANgIAA0AgAEEXSQRAIABBAnRBkJYCakEANgIEQQAhAQNAIAFBEEkEQCAAQQR0IAFqQQJ0QZCWAmpBADYCYCABQQFqIQEMAQsLIABBAWohAAwBCwtBkJYCQbSiAj8ArEIQhhALQZCWAiQJC6sDAQJ/AkACQAJAAkAjAg4DAAECAwtBASQCQQAkAxACIwYkBSMDDwsjB0UhASMFKAIEQXxxIQADQCAAIwZHBEAgACQFIAEgACgCBEEDcUcEQCAAIAEQA0EAJAMgAEEUahAZIwMPCyAAKAIEQXxxIQAMAQsLQQAkAxACIwYjBSgCBEF8cUYEQCMMIQADQCAAQYyWAkkEQCAAKAIAEAggAEEEaiEADAELCyMFKAIEQXxxIQADQCAAIwZHBEAgASAAKAIEQQNxRwRAIAAgARADIABBFGoQGQsgACgCBEF8cSEADAELCyMIIQAjBiQIIAAkBiABJAcgACgCBEF8cSQFQQIkAgsjAw8LIwUiACMGRwRAIAAoAgRBfHEkBSAAKAIEGiAAQYyWAkkEQCAAQQA2AgQgAEEANgIIBSMAIAAoAgBBfHFBBGprJAAgAEEEaiIAQYyWAk8EQCMJRQRAEAwLIABBBGshASAAQQ9xQQEgABsEf0EBBSABKAIAQQFxCxogASABKAIAQQFyNgIAIwkgARAKCwtBCg8LIwYjBjYCBCMGIwY2AghBACQCC0EACyAAIABB/v///wFJBH8gAEEBQRsgAGdrdGpBAWsFIAALC44BAQJ/IAFBgAJJBH8gAUEEdgVBHyABEA4iAWdrIgNBB2shAiABIANBBGt2QRBzCyEBIAAgAkECdGooAgRBfyABdHEiAQR/IAAgAWggAkEEdGpBAnRqKAJgBSAAKAIAQX8gAkEBanRxIgEEfyAAIAAgAWgiAEECdGooAgRoIABBBHRqQQJ0aigCYAVBAAsLC5gCAQN/IAFB/P///wNLBEBBgA5B0BBBzQNBHRAAAAsgAEEMIAFBE2pBcHFBBGsgAUEMTRsiARAPIgJFBEAgAUGAAk8EfyABEA4FIAELIQI/ACIDIAJBBCAAKAKgDCADQRB0QQRrR3RqQf//A2pBgIB8cUEQdiICIAIgA0gbQABBAEgEQCACQABBAEgEQAALCyAAIANBEHQ/AKxCEIYQCyAAIAEQDyECCyACKAIAGiAAIAIQCSACKAIAIgNBfHEgAWsiBEEQTwRAIAIgASADQQJxcjYCACACQQRqIAFqIgEgBEEEa0EBcjYCACAAIAEQCgUgAiADQX5xNgIAIAJBBGogAigCAEF8cWoiACAAKAIAQX1xNgIACyACC7EBAQF/IABB7P///wNPBEBBgA5BwA5BhQJBHxAAAAsjACMBTwRAAkBBgBAhAgNAIAIQDWshAiMCRQRAIwCtQsgBfkLkAICnQYAIaiQBDAILIAJBAEoNAAsjACMAIwFrQYAISUEKdGokAQsLIwlFBEAQDAsjCSAAQRBqEBAiAiABNgIMIAIgADYCECACIwgjBxAGIwAgAigCAEF8cUEEamokACACQRRqIgFBACAA/AsAIAELRwAgAUUEQA8LIwcgAUEUayIBKAIEQQNxRgRAIABBFGsoAgRBA3EiACMHRUYEQCABEAcFIwJBAUYgAEEDRnEEQCABEAcLCwsLDwAgACABNgIAIAAgARASC7ICAQJ/IAAgAUEBdGohAyACIQEDQCAAIANJBEAgAC8BACICQYABSQR/IAEgAjoAACABQQFqBSACQYAQSQR/IAEgAkEGdkHAAXIgAkE/cUGAAXJBCHRyOwEAIAFBAmoFIAJBgLgDSSAAQQJqIANJcSACQYDwA3FBgLADRnEEQCAALwECIgRBgPgDcUGAuANGBEAgASACQf8HcUEKdEGAgARqIARB/wdxciICQT9xQYABckEYdCACQQZ2QT9xQYABckEQdHIgAkEMdkE/cUGAAXJBCHRyIAJBEnZB8AFycjYCACABQQRqIQEgAEEEaiEADAULCyABIAJBDHZB4AFyIAJBBnZBP3FBgAFyQQh0cjsBACABIAJBP3FBgAFyOgACIAFBA2oLCyEBIABBAmohAAwBCwsLRgECfyABIABBFGsiAygCAEF8cUEQa00EQCADIAE2AhAgAA8LIAEgAygCDBARIgIgACABIAMoAhAiACAAIAFLG/wKAAAgAgs4AQF/IAAEQCAAQRRrIgEoAgRBA3FBA0YEQEHwFEHADkHSAkEHEAAACyABEAUgASMEQQMQBgsgAAtDACAARQRADwsgAEEUayIAKAIEQQNxQQNHBEBBsBVBwA5B4AJBBRAAAAsjAkEBRgRAIAAQBwUgABAFIAAjCCMHEAYLCzkAIwJBAEoEQANAIwIEQBANGgwBCwsLEA0aA0AjAgRAEA0aDAELCyMArULIAX5C5ACAp0GACGokAQtpAAJAAkACQAJAAkACQAJAAkAgAEEIaygCAA4KAAECBwYGBwMGBAULDwsPCw8LDwsPCwALIwxBBGskDBAbIwxBADYCACMMIAA2AgAgACgCABAIIwxBBGokDA8LIAAoAgAiAARAIAAQCAsLJgA/AEEQdEGMlgJrQQF2JAFB8A4QASQEQZAPEAEkBkGgEBABJAgLGgAjDEGMFkgEQEGglgJB0JYCQQFBARAAAAsLtgEBAX8jDEEQayQMEBsjDEIANwMAIwxCADcDCCAARQRAIwxBDEEDEBEiADYCAAsjDCAANgIEIABBABATIwwgADYCBCAAQQA2AgQjDCAANgIEIABBADYCCCABQfz///8DSwRAQZANQcANQRNBORAAAAsjDCABQQEQESICNgIIIwwgADYCBCMMIAI2AgwgACACEBMjDCAANgIEIAAgAjYCBCMMIAA2AgQgACABNgIIIwxBEGokDCAACz4BAX8jDEEIayQMEBsjDEIANwMAIwxBDEEGEBEiATYCACMMIAE2AgQjDCABIAAQHCIANgIAIwxBCGokDCAAC08AIwxBBGskDBAbIwxBADYCACMMIAA2AgAgASAAKAIMTwRAQcAPQZARQfIAQSoQAAALIwwgADYCACAAKAIEIAFqLQAAIQAjDEEEaiQMIAALTQAjDEEEayQMEBsjDEEANgIAIwwgADYCACABIAAoAghPBEBBwA9BwBFBsgFBLRAAAAsjDCAANgIAIAAoAgQgAWogAjoAACMMQQRqJAwLugEBBH8jDEEMayQMEBsjDEIANwMAIwxBADYCCCMMQaALNgIAIwxBBGskDBAbIwxBADYCACMMQaALNgIAQawLKAIAIQIjDEEEaiQMIwwgAhAdIgE2AgQDQCAAIAJIBEAjDCABNgIAIwxBoAs2AghBoAsgABAeIQMjDEGADDYCCEGADCAAEB4gA3MhAyMMQeAMNgIIIAEgAEHgDCAAEB4gA3NB/wFxEB8gAEEBaiEADAELCyMMQQxqJAwgAQuAAgEEfyMMQQRrJAwQGyMMQQA2AgACQAJAIwpBAWsOAwEBAQALAAsjDCAANgIAIwxBCGskDBAbIwxCADcDACMMIAA2AgAgACIBQRRrKAIQIAFqIQMDQCABIANJBEAgAS8BACIEQYABSQR/IAJBAWoFIARBgBBJBH8gAkECagUgBEGA+ANxQYCwA0YgAUECaiADSXEEQCABLwECQYD4A3FBgLgDRgRAIAJBBGohAiABQQRqIQEMBQsLIAJBA2oLCyECIAFBAmohAQwBCwsjDCACQQEQESIBNgIEIwwgADYCACAAIABBFGsoAhBBAXYgARAUIwxBCGokDCMMQQRqJAwgAQspACMMQQRrJAwQGyMMQQA2AgAjDCAANgIAIAAoAgghACMMQQRqJAwgAAtPACMMQQRrJAwQGyMMQQA2AgAjDCAANgIAIAEgACgCCE8EQEHAD0HAEUGnAUEtEAAACyMMIAA2AgAgACgCBCABai0AACEAIwxBBGokDCAAC1MAIwxBBGskDBAbIwxBADYCACMMIAA2AgAgASAAQRRrKAIQQQJ2TwRAQcAPQfASQd0AQSkQAAALIwwgADYCACAAIAFBAnRqIAI2AgAjDEEEaiQMC04AIwxBBGskDBAbIwxBADYCACMMIAA2AgAgASAAQRRrKAIQQQJ2TwRAQcAPQfASQc4AQSkQAAALIAAgAUECdGooAgAhACMMQQRqJAwgAAtSACMMQQRrJAwQGyMMQQA2AgAjDCAANgIAIAEgACgCDE8EQEHAD0GQEUHyAEEqEAAACyMMIAA2AgAgACgCBCABQQJ0aigCACEAIwxBBGokDCAAC64BAQJ/IwxBBGskDBAbIwxBADYCACMMIAA2AgAgASAAKAIIIgNBAnZLBEAgAUH/////AEsEQEGQDUGQEUETQTAQAAALIwwgADYCACAAKAIAIgJB/P///wMgA0EBdCIDIANB/P///wNPGyIDQQggASABQQhNG0ECdCIBIAEgA0kbIgEQFSIDIAJHBEAgACADNgIAIAAgAzYCBCAAIAMQEgsgACABNgIICyMMQQRqJAwLcwEBfyMMQQRrJAwQGyMMQQA2AgAjDCAANgIAIAEgACgCDE8EQCABQQBIBEBBwA9BkBFBggFBFhAAAAsgACABQQFqIgMQJyMMIAA2AgAgACADNgIMCyMMIAA2AgAgACgCBCABQQJ0aiACNgIAIwxBBGokDAvVCgIWfwF+IwxBIGskDBAbIwxBAEEg/AsAIwwgADYCACAAECKsQgOGIRcjDCAANgIAQcAAIAAQIkEJakHAAG9rIQEjDCAANgIAIAAQIiABQQAgAUHAAEcbakEJaiEUIwwgFBAdIhI2AgQDQCMMIAA2AgAgABAiIAJKBEAjDCASNgIAIwwgADYCCCASIAIgACACECMQHyACQQFqIQIMAQsLIwwgEjYCACMMIAA2AgggEiAAECJBgAEQH0EAIQADQCAAQQhIBEAjDCASNgIAIBIgFEEBayAAayAXIACsQgOGiEL/AYOnEB8gAEEBaiEADAELC0HnzKfQBiEIQYXdntt7IQlB8ua74wMhCkG66r+qeiELQf+kuYgFIQxBjNGV2HkhDUGrs4/8ASEOQZmag98FIQ8jDCEAIwxBBGskDBAbIwxBADYCACMMQYACQQcQESIRNgIAIwxBBGokDCAAIBE2AgwDQCAUIBVKBEBBACECA0AgAkEQSARAIwwgETYCACMMIBI2AgggEiAVIAJBAnRqIgEQI0EYdCEAIwwgEjYCCCAAIBIgAUEBahAjQRB0ciEAIwwgEjYCCCAAIBIgAUECahAjQQh0ciEAIwwgEjYCCCARIAIgEiABQQNqECMgAHIQJCACQQFqIQIMAQsLQRAhAQNAIAFBwABIBEAjDCARNgIAIBEgAUEPaxAlIQIjDCARNgIAIBEgAUEPaxAlIQAjDCARNgIAIAJBGXQgAkEHdnIgAEEOdCAAQRJ2cnMgESABQQ9rECVBA3ZzIQMjDCARNgIAIBEgAUECaxAlIQIjDCARNgIAIBEgAUECaxAlIQAjDCARNgIAIAJBD3QgAkERdnIgAEENdCAAQRN2cnMgESABQQJrECVBCnZzIQIjDCARNgIAIwwgETYCCCARIAFBEGsQJSADaiEAIwwgETYCCCARIAEgESABQQdrECUgAGogAmoQJCABQQFqIQEMAQsLIAghBCAJIQEgCiEDIAshByAMIQUgDSECIA4hACAPIQZBACETA0AgE0HAAEgEQCMMQcAKNgIAQcAKIBMQJiAGIAVBB3QgBUEZdnIgBUEadCAFQQZ2ciAFQRV0IAVBC3Zyc3NqIAIgBXEgBUF/cyAAcXNqaiEQIwwgETYCACAEQQp0IARBFnZyIARBHnQgBEECdnIgBEETdCAEQQ12cnNzIAEgA3EgASAEcSADIARxc3NqIRYgACEGIAIhACAFIQIgByARIBMQJSAQaiIQaiEFIAMhByABIQMgBCEBIBAgFmohBCATQQFqIRMMAQsLIAQgCGohCCABIAlqIQkgAyAKaiEKIAcgC2ohCyAFIAxqIQwgAiANaiENIAAgDmohDiAGIA9qIQ8gFUFAayEVDAELCyMMQSAQHSIENgIQIwwhAyMMIQEjDEEEayQMEBsjDEEANgIAIwxBIEEBEBEiADYCAEEQQQQQESICIAA2AgAgAiAAEBIgAiAANgIEIAJBIDYCCCACQQg2AgwjDEEEaiQMIAEgAjYCFCMMIAIoAgQ2AhggAkEAIAgQKCACQQEgCRAoIAJBAiAKECggAkEDIAsQKCACQQQgDBAoIAJBBSANECggAkEGIA4QKCACQQcgDxAoIAMgAjYCHEEAIQMDQCADQQhIBEAjDCACNgIAIAIgAxAmIQEjDCAENgIAIAQgA0ECdCIAIAFBGHYQHyMMIAQ2AgAgBCAAQQFqIAFBEHZB/wFxEB8jDCAENgIAIAQgAEECaiABQQh2Qf8BcRAfIwwgBDYCACAEIABBA2ogAUH/AXEQHyADQQFqIQMMAQsLIwxBIGokDCAEC0MAIwxBBGskDBAbIwxBADYCACMMIAA2AgAgASAAQRRrKAIQQQF2TwR/QX8FIAAgAUEBdGovAQALIQAjDEEEaiQMIAALTgAjDEEEayQMEBsjDEEANgIAIwwgADYCACABIABBFGsoAhBBAnZPBEBBwA9B8BJBzgBBKRAAAAsgACABQQJ0aigCACEAIwxBBGokDCAAC6oBAQN/IwxBCGskDBAbIwxCADcDACMMIAA2AgAjDCABNgIEIwxBCGskDBAbIwxCADcDACMMIAAiAjYCACAAQRRrKAIQQX5xIQMjDCABNgIAAkAgAUEUaygCEEF+cSIEIANqIgBFBEAjDEEIaiQMQdAUIQAMAQsjDCAAQQIQESIANgIEIAAgAiAD/AoAACAAIANqIAEgBPwKAAAjDEEIaiQMCyMMQQhqJAwgAAuqBQEHfyMMQRRrJAwQGyMMQQBBFPwLACMMIQMjDEEEayQMEBsjDEEANgIAIwxBgAhBCRARIgI2AgAjDEEEaiQMIAMgAjYCAANAIAFBgAJIBEAjDCACNgIEIAIgAUF/ECQgAUEBaiEBDAELC0EAIQEDQCMMQbATNgIEIAFBrBMoAgBBAXZIBEAjDCACNgIEIwxBsBM2AgggAkGwEyABECogARAkIAFBAWohAQwBCwtB0BQhAyMMQdAUNgIMQQAhAQNAIwwgADYCBCABIABBFGsoAhBBAXZIBEACQCMMIAA2AgQgACABECoiBUE9Rg0AIwwgAjYCBCACIAUQK0EATgRAIwwgAzYCBCMMIQZBASQKIwxBBGskDBAbIwxBADYCACMMQQJBAhARIgc2AgAgByAFOwEAIwxBBGokDCMMIAc2AgggBiADIAcQLCIDNgIMCyABQQFqIQEMAgsLCyMMIAM2AgQjDCADQRRrKAIQQQF2IgFBA2xBAnUiBRAdIgY2AhBBACEAA0AgASAESgRAIwwgAjYCBCMMIAM2AgggAiADIAQQKhArQRJ0IARBAWoiByABSAR/IwwgAjYCBCMMIAM2AgggAiADIAcQKhArBUEAC0EMdHIgBEECaiIHIAFIBH8jDCACNgIEIwwgAzYCCCACIAMgBxAqECsFQQALQQZ0ciAEQQNqIgcgAUgEfyMMIAI2AgQjDCADNgIIIAIgAyAHECoQKwVBAAtyIQcgACAFSARAIwwgBjYCBCAGIAAgB0EQdUH/AXEQHyAAQQFqIQALIAAgBUgEQCMMIAY2AgQgBiAAIAdBCHVB/wFxEB8gAEEBaiEACyAAIAVIBEAjDCAGNgIEIAYgACAHQf8BcRAfIABBAWohAAsgBEEEaiEEDAELCyMMQRRqJAwgBguNBQEIfyMMQSRrJAwQGyMMQQBBJPwLACMMECAiCTYCACMMIAA2AgRBASQKIwwgABAhIgg2AggjDCEHIwwgCDYCBEEBJAojDEEEayQMEBsjDEEANgIAAkACQAJAIwpBAWsOAwEBAgALAAtBfyECCyMMIAg2AgAjDEEMayQMEBsjDEIANwMAIwxBADYCCCMMIAg2AgAjDCAINgIEIAhBFGsoAhAhAyACIgBBAEgEQCAAQX9GBH8gAwVBkA1BwBFBzQ5BBxAAAAshAAUgACADSgRAQZANQcARQdIOQQcQAAALCyMMQQxBBhARIgI2AgggAiAINgIAIAIgCBASIAIgADYCCCACIAg2AgQjDEEMaiQMIwxBBGokDCAHIAI2AgwjDCAJNgIEIwwhACAJECIhAyMMIAI2AgQgACACECIgA2oQHSIANgIQA0AjDCAJNgIEIAkQIiAFSgRAIwwgADYCBCMMIAk2AhQgACAFIAkgBRAjEB8gBUEBaiEFDAELCwNAIwwgAjYCBCACECIgBkoEQCMMIAA2AgQjDCAJNgIUIAkQIiAGaiEDIwwgAjYCFCAAIAMgAiAGECMQHyAGQQFqIQYMAQsLIwwgADYCBCMMIAAQKSIANgIYIwwgATYCBCMMIAEQLSIBNgIcIwwgATYCBCABECIhAiMMIAIQHSIDNgIgA0AgAiAESgRAIwwgAzYCBCMMIAE2AhQgASAEECMhBSMMIAA2AhQgAyAEIAAgBEEgbxAjIAVzQf8BcRAfIARBAWohBAwBCwsjDCADNgIUIwwgAygCACIANgIEIwxBBGskDBAbIwxBADYCACMMIAA2AgAgACAAQRRrKAIQEC8hACMMQQRqJAwjDEEkaiQMIAAL0wIBBX8jDEEEayQMEBsjDEEANgIAIAAgAWohBCMMIAFBAXRBAhARIgI2AgAgAiEBA0AgACAESQRAAkAgAC0AACEFIABBAWohACAFQYABcQRAIAAgBEYNASAALQAAQT9xIQYgAEEBaiEAIAVB4AFxQcABRgRAIAEgBUEfcUEGdCAGcjsBAAUgACAERg0CIAAtAABBP3EhAyAAQQFqIQAgBUHwAXFB4AFGBEAgBUEPcUEMdCAGQQZ0ciADciEDBSAAIARGDQMgAC0AAEE/cSAFQQdxQRJ0IAZBDHRyIANBBnRyciEDIABBAWohAAsgA0GAgARJBEAgASADOwEABSABIANBgIAEayIDQQp2QYCwA3IgA0H/B3FBgLgDckEQdHI2AgAgAUECaiEBCwsFIAEgBTsBAAsgAUECaiEBDAILCwsgAiABIAJrEBUhACMMQQRqJAwgAAsqACMMQQhrJAwQGyMMIAA2AgAjDCABNgIEIAAgARAuIQAjDEEIaiQMIAALC+4LMQBBjAgLAhwBAEGYCAuIAgEAAAAAAQAAmC+KQpFEN3HP+8C1pdu16VvCVjnxEfFZpII/ktVeHKuYqgfYAVuDEr6FMSTDfQxVdF2+cv6x3oCnBtybdPGbwcFpm+SGR77vxp3BD8yhDCRvLOktqoR0StypsFzaiPl2UlE+mG3GMajIJwOwx39Zv/ML4MZHkafVUWPKBmcpKRSFCrcnOCEbLvxtLE0TDThTVHMKZbsKanYuycKBhSxykqHov6JLZhqocItLwqNRbMcZ6JLRJAaZ1oU1DvRwoGoQFsGkGQhsNx5Md0gntbywNLMMHDlKqthOT8qcW/NvLmjugo90b2OleBR4yIQIAseM+v++kOtsUKT3o/m+8nhxxgBBrAoLASwAQbgKCxUEAAAAEAAAACAEAAAgBAAAAAEAAEAAQdwKCwEsAEHoCgsiAQAAABoAAAA25SiuCyk++LpG+5yGc10duJ/Htbest+75tgBBjAsLASwAQZgLCxUFAAAAEAAAAHAFAABwBQAAGgAAABoAQbwLCwEsAEHICwsiAQAAABoAAAClWO6rC4o33qzShATyIXxSlZns8mR1Y4Yi6ABB7AsLASwAQfgLCxUFAAAAEAAAANAFAADQBQAAGgAAABoAQZwMCwEsAEGoDAsiAQAAABoAAADg1a9sZ8d4X3/jSf0QIUYuVGJff+S8pR/vbABBzAwLASwAQdgMCxUFAAAAEAAAADAGAAAwBgAAGgAAABoAQfwMCwEsAEGIDQsjAgAAABwAAABJAG4AdgBhAGwAaQBkACAAbABlAG4AZwB0AGgAQawNCwE8AEG4DQstAgAAACYAAAB+AGwAaQBiAC8AYQByAHIAYQB5AGIAdQBmAGYAZQByAC4AdABzAEHsDQsBPABB+A0LLwIAAAAoAAAAQQBsAGwAbwBjAGEAdABpAG8AbgAgAHQAbwBvACAAbABhAHIAZwBlAEGsDgsBPABBuA4LJwIAAAAgAAAAfgBsAGkAYgAvAHIAdAAvAGkAdABjAG0AcwAuAHQAcwBBrA8LATwAQbgPCysCAAAAJAAAAEkAbgBkAGUAeAAgAG8AdQB0ACAAbwBmACAAcgBhAG4AZwBlAEHsDwsBLABB+A8LGwIAAAAUAAAAfgBsAGkAYgAvAHIAdAAuAHQAcwBBvBALATwAQcgQCyUCAAAAHgAAAH4AbABpAGIALwByAHQALwB0AGwAcwBmAC4AdABzAEH8EAsBLABBiBELIQIAAAAaAAAAfgBsAGkAYgAvAGEAcgByAGEAeQAuAHQAcwBBrBELATwAQbgRCysCAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEHsEQsBPABB+BELKwIAAAAkAAAAVQBuAHAAYQBpAHIAZQBkACAAcwB1AHIAcgBvAGcAYQB0AGUAQawSCwEsAEG4EgsjAgAAABwAAAB+AGwAaQBiAC8AcwB0AHIAaQBuAGcALgB0AHMAQdwSCwE8AEHoEgstAgAAACYAAAB+AGwAaQBiAC8AcwB0AGEAdABpAGMAYQByAHIAYQB5AC4AdABzAEGcEwsBnABBqBMLhwECAAAAgAAAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAMAAxADIAMwA0ADUANgA3ADgAOQArAC8AQbwUCwEcAEHIFAsBAgBB3BQLATwAQegUCzECAAAAKgAAAE8AYgBqAGUAYwB0ACAAYQBsAHIAZQBhAGQAeQAgAHAAaQBuAG4AZQBkAEGcFQsBPABBqBULLwIAAAAoAAAATwBiAGoAZQBjAHQAIABpAHMAIABuAG8AdAAgAHAAaQBuAG4AZQBkAEHgFQsqCgAAACAAAAAgAAAAIAAAAAAAAAACAQAAQgAAAEEAAAAkAQAAAgkAACQJ";

// ─── Viduki (1shows) ─────────────────────────────────────────────────────────
// Their frontend WASM (makima.wasm) does all crypto. Exports are hashed but
// we recovered the arg orders from viduki-recon/. Session state is held in
// module-scope so the same Worker isolate can reuse the pepper for ~60s.
const VIDUKI_EXPORT_MAP = {
  alloc: '_gMLw', reset: '_6vB7', writeByte: '_G03w', readByte: '_xHqE',
  decryptPepper: '_aYur', decryptEnvelope: '_hmkb'
};
const VIDUKI_SPOOF = {
  'Origin': 'https://www.viduki.net',
  'Referer': 'https://www.viduki.net/',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    + ' (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
  'Accept': 'application/json',
  'Accept-Encoding': 'identity'
};

let vidukiWasmPromise = null;
let vidukiSession = null;         // { bootNonce, expiresAt }
let vidukiSessionPromise = null;  // in-flight bootstrap

function vidukiEnsureWasm() {
  if (vidukiWasmPromise) return vidukiWasmPromise;
  vidukiWasmPromise = (async () => {
    const bytes = b64ToBytes(MAKIMA_WASM_B64);
    const { instance } = await WebAssembly.instantiate(bytes, {
      env: { abort: () => { throw new Error('viduki wasm abort'); } }
    });
    const w = {};
    for (const [k, v] of Object.entries(VIDUKI_EXPORT_MAP)) w[k] = instance.exports[v];
    return w;
  })();
  return vidukiWasmPromise;
}

async function vidukiGet(url, extra = {}) {
  const res = await fetch(url, { headers: { ...VIDUKI_SPOOF, ...extra } });
  const body = await res.text();
  return { status: res.status, body };
}

function vidukiSolveAltcha(c) {
  const salt = c.salt;
  const target = c.challenge;
  const max = c.maxnumber || 200000;
  for (let n = 0; n <= max; n++) {
    if (sha256Hex(salt + n) === target) return n;
  }
  throw new Error('altcha unsolvable');
}
function vidukiMakeAltcha(c, n) {
  const s = JSON.stringify({
    algorithm: c.algorithm, challenge: c.challenge, number: n,
    salt: c.salt, signature: c.signature, took: 100
  });
  return btoa(s);
}

function vCopyIn(w, data) {
  const ptr = w.alloc(data.length);
  for (let i = 0; i < data.length; i++) w.writeByte(ptr, i, data[i]);
  return ptr;
}
function vCopyOut(w, ptr, len) {
  const out = new Uint8Array(len);
  for (let i = 0; i < len; i++) out[i] = w.readByte(ptr, i);
  return out;
}

/**
 * Full bootstrap: ALTCHA #1 → /bootstrap → ALTCHA #2 → /pepper-key → WASM
 * pepper decrypt. Session (bootNonce + WASM internal pepper) is good for ~60s.
 */
async function vidukiFreshSession() {
  const w = await vidukiEnsureWasm();
  const c1 = JSON.parse((await vidukiGet('https://api.viduki.net/altcha-challenge')).body);
  const boot = await vidukiGet('https://api.viduki.net/bootstrap',
    { 'x-altcha': vidukiMakeAltcha(c1, vidukiSolveAltcha(c1)) });
  const bootNonce = JSON.parse(boot.body).n;
  if (!bootNonce) throw new Error('no bootstrap nonce');

  const c2 = JSON.parse((await vidukiGet('https://api.viduki.net/altcha-challenge')).body);
  const pk = JSON.parse((await vidukiGet('https://api.viduki.net/pepper-key',
    { 'x-altcha': vidukiMakeAltcha(c2, vidukiSolveAltcha(c2)), 'x-nonce': bootNonce })).body);
  if (!pk || !pk.iv) throw new Error('bad pepper envelope');

  w.reset();
  const tbBuf = new Uint8Array(8);
  new DataView(tbBuf.buffer).setBigInt64(0, BigInt(pk.bucket), false);
  const nonceBytes = hexToBytes(bootNonce);
  const iv = hexToBytes(pk.iv), ct = hexToBytes(pk.ct), tag = hexToBytes(pk.tag);
  const rc = w.decryptPepper(
    vCopyIn(w, nonceBytes), nonceBytes.length,
    vCopyIn(w, tbBuf), 8,
    vCopyIn(w, iv), iv.length,
    vCopyIn(w, ct), ct.length,
    vCopyIn(w, tag), tag.length
  );
  if (rc <= 0) throw new Error('pepper decrypt failed');
  vidukiSession = { bootNonce, expiresAt: Date.now() + 60000 };
  return vidukiSession;
}

function vidukiGetSession() {
  if (vidukiSession && vidukiSession.expiresAt > Date.now()) return Promise.resolve(vidukiSession);
  if (vidukiSessionPromise) return vidukiSessionPromise;
  vidukiSessionPromise = vidukiFreshSession()
    .finally(() => { vidukiSessionPromise = null; });
  return vidukiSessionPromise;
}

/** Fetch and decrypt any /main/* envelope. Returns the parsed plaintext JSON. */
async function vidukiFetchEnvelope(pathAndQuery) {
  const w = await vidukiEnsureWasm();
  for (let attempt = 0; attempt < 2; attempt++) {
    const sess = await vidukiGetSession();
    const cn = randomBytes(16);
    const rid = randomBytes(16);
    const res = await vidukiGet('https://api.viduki.net' + pathAndQuery, {
      'x-nonce': sess.bootNonce,
      'x-client-nonce': bytesToHex(cn),
      'x-request-id': bytesToHex(rid)
    });
    if (res.status !== 200) {
      vidukiSession = null;
      if (attempt === 1) throw new Error(`viduki HTTP ${res.status}`);
      continue;
    }
    const env = JSON.parse(res.body);
    const tbBuf = new Uint8Array(8);
    new DataView(tbBuf.buffer).setBigInt64(0, BigInt(env.tb), false);
    const sn = hexToBytes(env.sn), iv2 = hexToBytes(env.iv2), wk = hexToBytes(env.wk);
    const tag2 = hexToBytes(env.tag2), iv1 = hexToBytes(env.iv1);
    const ctBytes = hexToBytes(env.ct), tag1 = hexToBytes(env.tag1);
    const outPtr = w.alloc(ctBytes.length);
    const outLen = w.decryptEnvelope(
      vCopyIn(w, cn), cn.length,
      vCopyIn(w, sn), 16,
      vCopyIn(w, tbBuf), 8,
      vCopyIn(w, rid), rid.length,
      vCopyIn(w, iv2), iv2.length,
      vCopyIn(w, wk), wk.length,
      vCopyIn(w, tag2), tag2.length,
      vCopyIn(w, iv1), iv1.length,
      vCopyIn(w, ctBytes), ctBytes.length,
      vCopyIn(w, tag1), tag1.length,
      outPtr
    );
    if (outLen <= 0) {
      vidukiSession = null;
      if (attempt === 1) throw new Error('envelope decrypt failed');
      continue;
    }
    return JSON.parse(new TextDecoder().decode(vCopyOut(w, outPtr, outLen)));
  }
  throw new Error('viduki: exhausted retries');
}

/**
 * Verify a viduki-resolved URL is actually playable. Some server tokens the
 * CDN has already invalidated (405/403/404); we can't tell from the encrypted
 * response alone, so we fetch the master playlist and check the first bytes.
 */
async function vidukiVerifyUrl(url) {
  try {
    const res = await fetch(url, {
      headers: {
        'Origin': 'https://www.viduki.net',
        'Referer': 'https://www.viduki.net/',
        'User-Agent': VIDUKI_SPOOF['User-Agent'],
        'Accept': '*/*'
      }
    });
    if (!res.ok) return false;
    const text = (await res.text()).trimStart();
    return text.startsWith('#EXTM3U');
  } catch (e) { return false; }
}

/**
 * Race a shortlist of server names in parallel through the WASM crypto path
 * and return the first one that also proves playable. Faster than serial
 * because we're bound by network + PoW, and both parallelize well.
 */
async function vidukiRaceServers(pathBase, servers) {
  const attempts = servers.map(async (srv) => {
    const plain = await vidukiFetchEnvelope(`${pathBase}?srv=${srv}`);
    const url = plain && plain.stream && plain.stream.url;
    if (!url) throw new Error(`${srv}: no url`);
    const ok = await vidukiVerifyUrl(url);
    if (!ok) throw new Error(`${srv}: unplayable`);
    return { srv, url };
  });
  return Promise.any(attempts);
}

async function handleViduki(url) {
  const suffix = url.pathname.slice('/viduki/'.length);
  const parts = suffix.split('/');
  let base;
  if (parts[0] === 'movie' && parts[1]) base = `/main/movie/${parts[1]}`;
  else if (parts[0] === 'tv' && parts[1] && parts[2] && parts[3]) {
    base = `/main/tv/${parts[1]}/${parts[2]}/${parts[3]}`;
  } else {
    return new Response(JSON.stringify({ error: 'usage: /viduki/movie/{id} or /viduki/tv/{id}/{s}/{e}' }),
      { status: 400, headers: CORS_HEADERS });
  }
  try {
    const servers = ['Ada', 'Claire', 'Ethan', 'Leon', 'Hunk', 'Nemesis'];
    const win = await vidukiRaceServers(base, servers);
    return new Response(JSON.stringify({
      sources: [{ url: win.url, quality: `Viduki HLS (${win.srv})` }],
      subtitles: []
    }), { status: 200, headers: CORS_HEADERS });
  } catch (agg) {
    const errs = agg && agg.errors;
    const msg = errs && errs.length ? errs.map(e => e.message).join(', ') : (agg && agg.message) || 'viduki failed';
    return new Response(JSON.stringify({ error: msg }), { status: 502, headers: CORS_HEADERS });
  }
}

// ─── Flickystream (goated.cx/1shows) ─────────────────────────────────────────
// Same 1shows backend as Viduki but no PoW, no bootstrap. The WASM (flicky.wasm)
// exports deobfuscate(n,d) which takes AssemblyScript strings (UTF-16LE with a
// 4-byte length prefix stored at ptr-4).
const FLICKY_SPOOF = {
  'Origin': 'https://flickystream.dad',
  'Referer': 'https://flickystream.dad/',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    + ' (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
  'Accept': '*/*'
};
let flickyWasmPromise = null;
function flickyEnsureWasm() {
  if (flickyWasmPromise) return flickyWasmPromise;
  flickyWasmPromise = (async () => {
    const bytes = b64ToBytes(FLICKY_WASM_B64);
    const { instance } = await WebAssembly.instantiate(bytes, {
      env: { abort: () => { throw new Error('flicky wasm abort'); } }
    });
    return instance;
  })();
  return flickyWasmPromise;
}
function flickyAllocString(inst, s) {
  const bytes = utf16leEncodeStr(s);
  const ptr = inst.exports.__new(bytes.length, 1);
  new Uint8Array(inst.exports.memory.buffer).set(bytes, ptr);
  return ptr;
}
function utf16leEncodeStr(s) {
  const out = new Uint8Array(s.length * 2);
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    out[i * 2] = c & 0xFF;
    out[i * 2 + 1] = (c >> 8) & 0xFF;
  }
  return out;
}
function flickyReadString(inst, ptr) {
  const mem = new Uint8Array(inst.exports.memory.buffer);
  const dv = new DataView(mem.buffer);
  const len = dv.getUint32(ptr - 4, true);
  let s = '';
  for (let i = 0; i < len; i += 2) s += String.fromCharCode(mem[ptr + i] | (mem[ptr + i + 1] << 8));
  return s;
}

async function flickyGet(url, extra = {}) {
  const res = await fetch(url, { headers: { ...FLICKY_SPOOF, ...extra } });
  const body = await res.text();
  return { status: res.status, body };
}

async function flickyResolveStream(mediaKind, tmdbId, season, episode, server) {
  const inst = await flickyEnsureWasm();
  const suffix = mediaKind === 'tv'
    ? `tv/${tmdbId}/${season || 1}/${episode || 1}`
    : `movie/${tmdbId}`;
  const res = await flickyGet(`https://api.flickystream.dad/api/streams/${suffix}?s=${encodeURIComponent(server)}`);
  if (res.status !== 200) throw new Error(`flicky HTTP ${res.status}`);
  const env = JSON.parse(res.body);
  if (!env || !env.n || !env.d) throw new Error('flicky: bad envelope');
  const nPtr = flickyAllocString(inst, env.n);
  const dPtr = flickyAllocString(inst, env.d);
  const resultPtr = inst.exports.deobfuscate(nPtr, dPtr);
  if (!resultPtr) throw new Error('flicky: deobfuscate returned null');
  return JSON.parse(flickyReadString(inst, resultPtr));
}

async function handleFlicky(url) {
  const suffix = url.pathname.slice('/flicky/'.length);
  const parts = suffix.split('/');
  let mediaKind, tmdbId, season, episode;
  if (parts[0] === 'movie' && parts[1]) {
    mediaKind = 'movie'; tmdbId = parts[1];
  } else if (parts[0] === 'tv' && parts[1] && parts[2] && parts[3]) {
    mediaKind = 'tv'; tmdbId = parts[1]; season = parts[2]; episode = parts[3];
  } else {
    return new Response(JSON.stringify({ error: 'usage: /flicky/movie/{id} or /flicky/tv/{id}/{s}/{e}' }),
      { status: 400, headers: CORS_HEADERS });
  }
  try {
    const trySrvs = ['tik', 'ipcloud', 'v4:English', 'v5:Hindi'];
    const attempts = trySrvs.map(async (srv) => {
      const plain = await flickyResolveStream(mediaKind, tmdbId, season, episode, srv);
      if (!plain || !plain.url) throw new Error(`${srv}: no url`);
      const ok = await vidukiVerifyUrl(plain.url);
      if (!ok) throw new Error(`${srv}: unplayable`);
      return { srv, url: plain.url };
    });
    const win = await Promise.any(attempts);
    return new Response(JSON.stringify({
      sources: [{ url: win.url, quality: `Flickystream HLS (${win.srv})` }],
      subtitles: []
    }), { status: 200, headers: CORS_HEADERS });
  } catch (agg) {
    const errs = agg && agg.errors;
    const msg = errs && errs.length ? errs.map(e => e.message).join(', ') : (agg && agg.message) || 'flicky failed';
    return new Response(JSON.stringify({ error: msg }), { status: 502, headers: CORS_HEADERS });
  }
}

// ─── Legacy TryBox/SpeedRace handler (unchanged behaviour, kept intact) ──────
async function handleTrybox(url) {
  const tmdbId = url.searchParams.get('id') || url.searchParams.get('tmdbId');
  const imdbId = url.searchParams.get('imdbId') || '';
  const title = encodeURIComponent(url.searchParams.get('title') || '');
  const type = url.searchParams.get('type') || url.searchParams.get('mediaType') || 'movie';
  const season = url.searchParams.get('season') || '1';
  const episode = url.searchParams.get('episode') || '1';
  const year = url.searchParams.get('year') || '';

  if (!tmdbId) {
    return new Response(JSON.stringify({ error: 'Missing TMDB ID parameter' }),
      { status: 400, headers: CORS_HEADERS });
  }
  try {
    const seedRes = await fetch(`${SPEEDRACE_HOST}/seed?mediaId=${tmdbId}`, {
      headers: { 'Origin': SPOOF_ORIGIN, 'Referer': SPOOF_ORIGIN + '/' }
    });
    if (!seedRes.ok) throw new Error(`Failed to fetch seed: status ${seedRes.status}`);
    const { seed } = await seedRes.json();
    const q = `title=${title}&mediaType=${type}&year=${year}&episodeId=${episode}&seasonId=${season}&tmdbId=${tmdbId}&imdbId=${imdbId}&enc=2&seed=${seed}`;
    const endpoints = [
      `${SPEEDRACE_HOST}/vsrc/sources-with-title?${q}`,
      `${SPEEDRACE_HOST}/cdn/sources-with-title?${q}`,
      `${SPEEDRACE_HOST}/hdmovie/sources-with-title?${q}`
    ];
    for (const ep of endpoints) {
      try {
        const res = await fetch(ep, {
          headers: { 'Origin': SPOOF_ORIGIN, 'Referer': SPOOF_ORIGIN + '/' }
        });
        if (!res.ok) continue;
        const encryptedText = await res.text();
        const jsonText = decryptPayload(encryptedText, seed, tmdbId);
        const parsed = JSON.parse(jsonText);
        if (parsed && parsed.sources && parsed.sources.length > 0) {
          return new Response(JSON.stringify({
            tmdbId,
            seed,
            sources: parsed.sources.map(src => ({
              provider: 'SpeedRace Direct',
              quality: src.quality || '1080p HD',
              url: src.url,
              isEmbed: false
            })),
            subtitles: parsed.subtitles || []
          }), { status: 200, headers: CORS_HEADERS });
        }
      } catch (e) {}
    }
    throw new Error('SpeedRace returned empty sources');
  } catch (err) {
    const fallbackUrl = type === 'movie'
      ? `https://player.videasy.to/movie/${tmdbId}`
      : `https://player.videasy.to/tv/${tmdbId}/${season}/${episode}`;
    return new Response(JSON.stringify({
      tmdbId,
      sources: [{ provider: 'Videasy Fallback', quality: '1080p Embed', url: fallbackUrl, isEmbed: true }],
      subtitles: []
    }), { status: 200, headers: CORS_HEADERS });
  }
}

// ─── Router ──────────────────────────────────────────────────────────────────
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS_HEADERS });

    if (url.pathname.startsWith('/viduki/')) return handleViduki(url);
    if (url.pathname.startsWith('/flicky/')) return handleFlicky(url);
    return handleTrybox(url);
  }
};
